name: Generate and Copy API Code

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Generate API code
        run: ./gradlew generateApi
      - name: Copy API files
        run: ./gradlew copyApiFilesIntoProject
