name: Generate and Copy API Code

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Generate API code
        run: ./gradlew generateApi
      - name: Copy API files
        run: ./gradlew copyApiFilesIntoProject
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically update API code"
          commit_options: "--no-verify"
          branch: main
          file_pattern: '**/*'
          file_ignore_pattern: '**/*.log'
